branch-defaults:
  default:
    environment: Udacityproject4fullstack-env
environment-defaults:
  Udacityproject4fullstack-env:
    branch: null
    repository: null
global:
  application_name: Udacity-project4-fullstack
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
deploy:
  artifact: www/Archive.zip