branch-defaults:
  master:
    environment: Udaproject4frontedn-env
global:
  application_name: Udaproject4frontedn
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2/5.4.8
  default_region: us-east-1
  sc: git
  workspace_type: Application
delopy:
  artifact: ./Archive.zip
