branch-defaults:
  master:
    environment: Uda-project4-frontend-env
environment-defaults:
  Udaproject4frontedn-env:
    branch: null
    repository: null
global:
  application_name: Uda-project4-frontend
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2/5.4.8
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
delopy:
  artifact: www/Archive.zip
